# escape=`
FROM czon/azdo-agent:$[AGENT_TAG]

LABEL name="czon/azdo-agent:$[AGENT_TAG]-vs2017-standard" `
      maintainer="CodeZ.one - Kirsten Kluge" `
      version="0.0.1"

#
# This is not complete jet and need some more work.
#

# Download the Build Tools bootstrapper outside of the PATH.
ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\\Setup\\vs_buildtools.exe
ADD https://aka.ms/vscollect.exe C:\\Setup\\collect.exe

# Use PowerShell commands to download, validate hashes, etc.
SHELL ["powershell.exe", "-ExecutionPolicy", "Bypass", "-Command", "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue'; $VerbosePreference = 'Continue';"]

RUN $ErrorActionPreference = 'Stop'; `
    $VerbosePreference = 'Continue'; `
    $p = Start-Process -Wait -PassThru -FilePath C:\Setup\vs_buildtools.exe -ArgumentList '--quiet --wait --norestart --nocache --installPath C:\BuildTools --all --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 --remove Microsoft.VisualStudio.Component.Windows81SDK'; `
    if ($ret = $p.ExitCode) { C:\Setup\collect.exe; throw ('Install failed with exit code 0x{0:x}' -f $ret) }

SHELL ["cmd.exe", "/s", "/c"]